# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/agent.AgentService/Configure',
                request_serializer=agent__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=agent__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.RunStep = channel.unary_stream(
                '/agent.AgentService/RunStep',
                request_serializer=agent__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__pb2.AgentEvent.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/agent.AgentService/Stop',
                request_serializer=agent__pb2.StopRequest.SerializeToString,
                response_deserializer=agent__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/agent.AgentService/GetHistory',
                request_serializer=agent__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=agent__pb2.GetHistoryResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/agent.AgentService/Health',
                request_serializer=agent__pb2.Ping.SerializeToString,
                response_deserializer=agent__pb2.Pong.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Configure(self, request, context):
        """Configure the agent with system prompt, tools, and settings.
        Must be called before RunStep to set up the agent for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStep(self, request, context):
        """Main entry point: run an agent step with user input.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop/interrupt a running agent step.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Get conversation history for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=agent__pb2.ConfigureRequest.FromString,
                    response_serializer=agent__pb2.ConfigureResponse.SerializeToString,
            ),
            'RunStep': grpc.unary_stream_rpc_method_handler(
                    servicer.RunStep,
                    request_deserializer=agent__pb2.RunRequest.FromString,
                    response_serializer=agent__pb2.AgentEvent.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=agent__pb2.StopRequest.FromString,
                    response_serializer=agent__pb2.StopResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=agent__pb2.GetHistoryRequest.FromString,
                    response_serializer=agent__pb2.GetHistoryResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agent__pb2.Ping.FromString,
                    response_serializer=agent__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/Configure',
            agent__pb2.ConfigureRequest.SerializeToString,
            agent__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.AgentService/RunStep',
            agent__pb2.RunRequest.SerializeToString,
            agent__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/Stop',
            agent__pb2.StopRequest.SerializeToString,
            agent__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/GetHistory',
            agent__pb2.GetHistoryRequest.SerializeToString,
            agent__pb2.GetHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/Health',
            agent__pb2.Ping.SerializeToString,
            agent__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
