// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/agentproto/agent.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_THOUGHT     EventType = 1
	EventType_EVENT_TYPE_TOOL_CALL   EventType = 2
	EventType_EVENT_TYPE_TOOL_RESULT EventType = 3
	EventType_EVENT_TYPE_ANSWER      EventType = 4
	EventType_EVENT_TYPE_ERROR       EventType = 5
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_THOUGHT",
		2: "EVENT_TYPE_TOOL_CALL",
		3: "EVENT_TYPE_TOOL_RESULT",
		4: "EVENT_TYPE_ANSWER",
		5: "EVENT_TYPE_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_THOUGHT":     1,
		"EVENT_TYPE_TOOL_CALL":   2,
		"EVENT_TYPE_TOOL_RESULT": 3,
		"EVENT_TYPE_ANSWER":      4,
		"EVENT_TYPE_ERROR":       5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_agentproto_agent_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_internal_agentproto_agent_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_internal_agentproto_agent_proto_rawDescGZIP(), []int{0}
}

type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED ServiceStatus = 0
	ServiceStatus_SERVICE_STATUS_OK          ServiceStatus = 1
	ServiceStatus_SERVICE_STATUS_BUSY        ServiceStatus = 2
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_OK",
		2: "SERVICE_STATUS_BUSY",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED": 0,
		"SERVICE_STATUS_OK":          1,
		"SERVICE_STATUS_BUSY":        2,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_agentproto_agent_proto_enumTypes[1].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_internal_agentproto_agent_proto_enumTypes[1]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_agentproto_agent_proto_rawDescGZIP(), []int{1}
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InputText     string                 `protobuf:"bytes,2,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_internal_agentproto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentproto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_internal_agentproto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunRequest) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

func (x *RunRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=agent.EventType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_internal_agentproto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentproto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_internal_agentproto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *AgentEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AgentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentEvent) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_agentproto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentproto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_agentproto_agent_proto_rawDescGZIP(), []int{2}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServiceStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=agent.ServiceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_agentproto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentproto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_agentproto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

var File_internal_agentproto_agent_proto protoreflect.FileDescriptor

const file_internal_agentproto_agent_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/agentproto/agent.proto\x12\x05agent\"\xc1\x01\n" +
	"\n" +
	"RunRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"input_text\x18\x02 \x01(\tR\tinputText\x129\n" +
	"\benv_vars\x18\x03 \x03(\v2\x1e.agent.RunRequest.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\n" +
	"AgentEvent\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.agent.EventTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\"\x06\n" +
	"\x04Ping\"4\n" +
	"\x04Pong\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.agent.ServiceStatusR\x06status*\xa2\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_THOUGHT\x10\x01\x12\x18\n" +
	"\x14EVENT_TYPE_TOOL_CALL\x10\x02\x12\x1a\n" +
	"\x16EVENT_TYPE_TOOL_RESULT\x10\x03\x12\x15\n" +
	"\x11EVENT_TYPE_ANSWER\x10\x04\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x05*_\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SERVICE_STATUS_OK\x10\x01\x12\x17\n" +
	"\x13SERVICE_STATUS_BUSY\x10\x022e\n" +
	"\fAgentService\x121\n" +
	"\aRunStep\x12\x11.agent.RunRequest\x1a\x11.agent.AgentEvent0\x01\x12\"\n" +
	"\x06Health\x12\v.agent.Ping\x1a\v.agent.PongB\x1eZ\x1cplatform/internal/agentprotob\x06proto3"

var (
	file_internal_agentproto_agent_proto_rawDescOnce sync.Once
	file_internal_agentproto_agent_proto_rawDescData []byte
)

func file_internal_agentproto_agent_proto_rawDescGZIP() []byte {
	file_internal_agentproto_agent_proto_rawDescOnce.Do(func() {
		file_internal_agentproto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agentproto_agent_proto_rawDesc), len(file_internal_agentproto_agent_proto_rawDesc)))
	})
	return file_internal_agentproto_agent_proto_rawDescData
}

var file_internal_agentproto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_agentproto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_agentproto_agent_proto_goTypes = []any{
	(EventType)(0),     // 0: agent.EventType
	(ServiceStatus)(0), // 1: agent.ServiceStatus
	(*RunRequest)(nil), // 2: agent.RunRequest
	(*AgentEvent)(nil), // 3: agent.AgentEvent
	(*Ping)(nil),       // 4: agent.Ping
	(*Pong)(nil),       // 5: agent.Pong
	nil,                // 6: agent.RunRequest.EnvVarsEntry
}
var file_internal_agentproto_agent_proto_depIdxs = []int32{
	6, // 0: agent.RunRequest.env_vars:type_name -> agent.RunRequest.EnvVarsEntry
	0, // 1: agent.AgentEvent.type:type_name -> agent.EventType
	1, // 2: agent.Pong.status:type_name -> agent.ServiceStatus
	2, // 3: agent.AgentService.RunStep:input_type -> agent.RunRequest
	4, // 4: agent.AgentService.Health:input_type -> agent.Ping
	3, // 5: agent.AgentService.RunStep:output_type -> agent.AgentEvent
	5, // 6: agent.AgentService.Health:output_type -> agent.Pong
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_agentproto_agent_proto_init() }
func file_internal_agentproto_agent_proto_init() {
	if File_internal_agentproto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agentproto_agent_proto_rawDesc), len(file_internal_agentproto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agentproto_agent_proto_goTypes,
		DependencyIndexes: file_internal_agentproto_agent_proto_depIdxs,
		EnumInfos:         file_internal_agentproto_agent_proto_enumTypes,
		MessageInfos:      file_internal_agentproto_agent_proto_msgTypes,
	}.Build()
	File_internal_agentproto_agent_proto = out.File
	file_internal_agentproto_agent_proto_goTypes = nil
	file_internal_agentproto_agent_proto_depIdxs = nil
}
